version: "3.8"
services:
  db:
    container_name: db
    image: "lyrasis/blazegraph:2.1.5"
    # Uncomment if you want to access blazegraph interface in your browser (http://localhost:8888) 
    #  ports:
    #   - 8888:8080
    volumes:
      - .:/app
      - ./blaze_vm.properties:/RWStore.properties
    restart: always

  sparqlanything:
    container_name: sparqlanything
    image: facadex/sparql-anything:latest
    ports:
      - "8081:3000"
    restart: always

  web:
    container_name: web
    build: .
    depends_on: 
      - db
    volumes:
      - .:/app
    expose:
      - 8080
    stdin_open: true
    tty: true
    command: ["/wait-for-it.sh", "db:8080", "--", "gunicorn", 
              "--workers", "4",
              "--threads","2",
              "--bind","0.0.0.0:8080", "app:wsgiapp"]
    environment: 
      - BLAZEGRAPH_ENDPOINT=http://db:8080/bigdata/sparql
      - SPARQL_ANYTHING_ENDPOINT=http://sparqlanything:3000/sparql.anything
      - PUBLIC_BLAZEGRAPH_ENDPOINT=http://localhost:8080/sparql
  nginx:
    build: ./services/nginx
    volumes:
      - ./static:/app/static
    ports:
      - 80:80
    depends_on:
      - web
