# version: "3.8" # not needed anymore
services:
  db:
    # container_name: db
    image: "lyrasis/blazegraph:2.1.5"
    # Uncomment if you want to access blazegraph interface in your browser (http://localhost:8888)
    ports:
      - "8112:8080"
    volumes:
      - .:/app
      - ./blaze_vm.properties:/RWStore.properties
    restart: always
  sparqlanything:
    # container_name: sparqlanything
    image: facadex/sparql-anything:latest
    ports:
      #- "8081:3000"
      - "8113:3000"
    restart: always
  init-static:
    image: busybox
    volumes:
      - static_data:/app/static
    command: ["/bin/sh", "-c", "cp -r /app/static_default/* /app/static || true"]
  web:
    # container_name: clef
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - sparqlanything
      - db
    volumes:
      - .:/app
      - static_data:/app/static  # Share static files with nginx
    ports:
      #- "8080:8080"
      - "8114:8080"
    stdin_open: true
    tty: true
    command:
      - "/wait-for-it.sh"
      - "db:8080"
      - "--"
      - "gunicorn"
      - "--workers=4"
      - "--threads=2"
      - "--bind=0.0.0.0:8080"
      - "app:wsgiapp"
    environment:
      BLAZEGRAPH_ENDPOINT: "http://db:8080/bigdata/sparql"
      SPARQL_ANYTHING_ENDPOINT: "http://sparqlanything:3000/sparql.anything"
      PUBLIC_BLAZEGRAPH_ENDPOINT: "http://localhost:8080/sparql"
    restart: unless-stopped
  nginx:
    container_name: clef
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.prod
    volumes:
      # - ./static:/app/static
      - static_data:/app/static
    ports:
      #- 80:80
      - "8115:80"
    depends_on:
      - web
    restart: unless-stopped
volumes:
  static_data:
  # blazegraph_data:
